### ISSUE TITLE
Option to ignore dotfiles

### ISSUE THREAD

**Issue by nabijaczleweli** [melak47/treesize-rs#1]
or ignore dotfiles by default and unignore via flag

**Comment by melak47** [comment]
Went with "ignore by default". Implemented in v0.2.0

**Comment by nabijaczleweli** [comment]
:shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit: :shipit:
