### ISSUE TITLE
Don't panic

### ISSUE THREAD

**Issue by melak47** [melak47/treesize-rs#6]
`treesize` shouldn't panic if some file or directory cannot be accessed (for any number of reasons - file no longer exists, permission denied...).
Maybe output warnings mentioning the path to stderr, record the size as 0, and move on?

**Comment by nabijaczleweli** [comment]
IME it doesn't panic but rather just tells me that

```sh
Error reading directory "C:\\ProgramData\\Microsoft\\Windows\\SystemData", caused by I/O error: Access is denied. (os error 5)
```

Do you have something reproducible?

**Comment by melak47** [comment]
It doesn't panic, but just prints an error and nothing else. That's what I meant.
