### ISSUE TITLE
Incorrect human readable metric prefixes

### ISSUE THREAD

**Issue by non-descriptive** [melak47/treesize-rs#9]
KB MB GB and other prefixes are stand for 10 power 2, 10 power 3 and so on. It's base 10 prefixes, but your code actually counts base 2 values, so human readable prefixes should be KiB, MiB and so on to display actual values.

**Comment by nabijaczleweli** [comment]
NB: released in [`v0.5.0`](https://github.com/melak47/treesize-rs/releases/tag/v0.5.0)
